CREATE TABLE IF NOT EXISTS boticario-hruthes.DIM.T_MARCAS
(
    ID_LINHA STRING NOT NULL,
    LINHA STRING NOT NULL,
    CREATED_AT DATE NOT NULL,
    MODIFIED_AT DATE NOT NULL,
    JOB_RUN_ID STRING NOT NULL
);
