CREATE TABLE IF NOT EXISTS boticario-hruthes.DIM.T_MARCAS
(
    ID_MARCA STRING NOT NULL,
    MARCA STRING NOT NULL,
    CREATED_AT DATE NOT NULL,
    MODIFIED_AT DATE NOT NULL,
    JOB_RUN_ID STRING NOT NULL
);
