--V_VENDAS_LINHA_MES_ANO
SELECT  IDLINHA ,LINHA, MES, ANO, SUM(QUANTIDADE) AS CONSOLIDADO_VENDAS, FROM `boticario-hruthes.CURATED_VENDAS.VENDAS` 
GROUP BY LINHA, IDLINHA, MES, ANO
ORDER BY MES, ANO, IDLINHA;