--V_VENDAS_MARCA_LINHA
SELECT SUM(QUANTIDADE) AS CONSOLIDADO_VENDAS, MARCA,IDMARCA, LINHA, IDLINHA FROM `boticario-hruthes.CURATED_VENDAS.VENDAS` 
GROUP BY MARCA, LINHA, IDMARCA, IDLINHA
ORDER BY IDMARCA;